### ISSUE TITLE
`resume_to` in `Yielder` discuss

### ISSUE THREAD

**Issue by dragon-zhang** [Amanieu/corosensei#10]
I'm trying to build a scheduler based on `corosensei` and I've come up with a place that can be optimized, but needs `corosensei` support.

current logic:
main thread -> coroutine1 -> main thread -> coroutine2 -> main thread -> end

better logic:
main thread -> coroutine1 -> coroutine2 -> main thread -> end

The times of jump between coroutines has become half, but need `Yielder` support `resume_to`.

As for `back_to_main`, maybe I can directly get the first coroutine in `scheduler` and just call `resume` ?

**Comment by Amanieu** [comment]
The problem is that corosensei is designed as an asymmetric coroutine API. This means that a coroutine can only yield back to its caller. This is an intentional design choice, since it provides many benefits:
- Backtraces can be linked to the parent context, for easier debugging.
- Panics in a coroutine will continue unwinding out of the parent's context.
- Support for trap recovery.

To switch to another corountine directly without a clear parent->child relationship, you need a symmetric coroutine API such as the one from [Boost.context](https://www.boost.org/doc/libs/1_80_0/libs/context/doc/html/context/cc.html). This loses many of the benefits listed above.

**Comment by dragon-zhang** [comment]
In fact, I have already done so in [open-coroutine-rs](https://github.com/dragon-zhang/open-coroutine-rs), but I have encountered some problems. Can you help me solve them?

**Comment by Amanieu** [comment]
I'm happy to help if you have any issues related to corosensei.

**Comment by dragon-zhang** [comment]
fine and thanks.
